# Generated by scripts/source-validation/generate.py
"""Release-identity proof for new_jersey_shipped_sources.

Every value recorded below is compared against the package's own state: the
generated Python module, and the release lock read from disk.
"""

import importlib.util
import json
from pathlib import Path

CONTRACT_ID = "new_jersey_shipped_sources"
SOURCE_VALIDATION_RELEASE = "source-validation-v1.0.0-rc.4"
CONTRACT_FINGERPRINT = "sha256:01384c3db08d508e202060996643cbf1f7c9c5b00c3d268f1fcb2ae97264b6f8"
ARTIFACT_MANIFEST_DIGEST = "sha256:a504663075c50fa7459965fc3a641935bac19e7fce0b67c6490dc915e46f5d8b"
EXPECTED_TEST_IDS = ["SV-001","SV-002","SV-003","SV-004","SV-005","SV-006","SV-007","SV-008","SV-009","SV-010","SV-011","SV-012","SV-013","SV-014","SV-015","SV-016","SV-017"]

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = (
    PACKAGE_ROOT
    / "inst"
    / "extdata"
    / "source-contract"
    / "contracts"
    / CONTRACT_ID
    / "release-lock.json"
)


def _read_lock():
    assert LOCK_PATH.is_file(), f"release lock is not installed: {LOCK_PATH}"
    return json.loads(LOCK_PATH.read_text(encoding="utf-8"))


def _load_generated_module():
    destination = _read_lock()["python_destination"]
    module_path = (
        PACKAGE_ROOT / destination / f"source_validation_{CONTRACT_ID}_generated.py"
    )
    assert module_path.is_file(), f"generated module is missing: {module_path}"
    spec = importlib.util.spec_from_file_location(
        f"_source_validation_{CONTRACT_ID}_generated", module_path
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_expected_test_ids_are_nonempty_and_unique():
    assert EXPECTED_TEST_IDS
    assert len(EXPECTED_TEST_IDS) == len(set(EXPECTED_TEST_IDS))


def test_generated_module_carries_the_recorded_identity():
    module = _load_generated_module()
    assert module.SOURCE_VALIDATION_RELEASE == SOURCE_VALIDATION_RELEASE
    assert module.CONTRACT_FINGERPRINT == CONTRACT_FINGERPRINT
    assert module.ARTIFACT_MANIFEST_DIGEST == ARTIFACT_MANIFEST_DIGEST
    assert module.EXPECTED_TEST_IDS == EXPECTED_TEST_IDS


def test_capture_tree_holds_nothing_but_the_declared_captures():
    """A capture no declaration names is evidence of nothing.

    The lock's own `fingerprint_sources` is checked against its own
    `generated_files` elsewhere -- two records that agree with each other by
    construction. This is the only assertion that reads the DIRECTORY, so it is
    the only one that can see a capture left behind when a declaration was
    renamed, moved between categories or dropped. `al` carried 33 such files and
    `hi` one, each looking exactly like real provenance to a reader.

    `__pycache__` is excluded deliberately: pytest writes it next to any
    captured test module it imports, so it appears after this tree was last
    written and belongs to the committed-junk sweep, not to provenance.
    """
    lock = _read_lock()
    declared = set(lock["fingerprint_sources"])
    assert declared, "the lock records no fingerprint captures at all"
    capture_root = LOCK_PATH.parent / "fingerprint-inputs"
    on_disk = {
        path.relative_to(PACKAGE_ROOT).as_posix()
        for path in capture_root.rglob("*")
        if path.is_file() and "__pycache__" not in path.parts
    }
    assert on_disk == declared


def test_release_lock_on_disk_matches_the_recorded_identity():
    lock = _read_lock()
    assert lock["contract_id"] == CONTRACT_ID
    assert lock["source_validation_release"] == SOURCE_VALIDATION_RELEASE
    assert lock["contract_fingerprint"] == CONTRACT_FINGERPRINT
    assert lock["artifact_manifest_digest"] == ARTIFACT_MANIFEST_DIGEST
    assert lock["expected_test_ids"] == EXPECTED_TEST_IDS
