---
title: "new_all_assess"
author: "Andrew Martin"
date: "August 11, 2015"
output: html_document
---

```{r}
library(devtools)
devtools::load_all(pkg = "C:\\Users\\AMartin\\Dropbox\\repositories\\njschooldata")
```

```{r}

assess_years <- structure(list(year = c(2014, 2014, 2014, 2014, 2014, 2014, 2014, 
2013, 2013, 2013, 2013, 2013, 2013, 2013, 2012, 2012, 2012, 2012, 
2012, 2012, 2012, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2010, 
2010, 2010, 2010, 2010, 2010, 2010, 2009, 2009, 2009, 2009, 2009, 
2009, 2009, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2007, 2007, 
2007, 2007, 2007, 2007, 2007, 2006, 2006, 2006, 2006, 2006, 2006, 
2006, 2005, 2005, 2005, 2005, 2004, 2004, 2004, 2004), grade = c(3, 
4, 5, 6, 7, 8, 11, 3, 4, 5, 6, 7, 8, 11, 3, 4, 5, 6, 7, 8, 11, 
3, 4, 5, 6, 7, 8, 11, 3, 4, 5, 6, 7, 8, 11, 3, 4, 5, 6, 7, 8, 
11, 3, 4, 5, 6, 7, 8, 11, 3, 4, 5, 6, 7, 8, 11, 3, 4, 5, 6, 7, 
8, 11, 3, 4, 8, 11, 3, 4, 8, 11), finished = c("NO", "NO", "NO", 
"NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", 
"NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", 
"NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", 
"NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", 
"NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", 
"NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", 
"NO", "NO")), .Names = c("year", "grade", "finished"), row.names = c(NA, 
-71L), class = "data.frame")

assess_years$name <- c(
  rep(c(rep('NJASK', 6), 'HSPA'), 7), 
  rep(c(rep('NJASK', 5),'GEPA', 'HSPA'), 2), 
  rep(c('NJASK', 'NJASK', 'GEPA', 'HSPA'), 2)
)

save(assess_years, file = 'assess_years.Rda')



```

it keeps crashing.  sigh.
```{r}

load(file = 'assess_years.Rda')

for (i in 1:nrow(assess_years)) {
  if (assess_years[i, 'finished'] == 'YES') {
    next()
  }

# these were for fixing parse problems on a one-off basis  
#   if (assess_years[i, 'year'] != 2004) {
#     next()
#   }
# 
#   if (assess_years[i, 'grade'] != 11) {
#     next()
#   }
  
  this_row <- assess_years[i, ]
  #be verbose
  row_key <- paste0('nj', this_row$year, 'gr', this_row$grade)
  print(row_key)
  
  #call this grade/year and attach to results list
  result <-  fetch_nj_assess(this_row$year, this_row$grade)

  save(assess_years, file = 'assess_years.Rda')
  try(saveRDS(result, file = paste0('nj-raw/', row_key, ".Rds")))

  assess_years[i, 'finished'] <- 'YES'

}

```

when finished, parse

```{r}

assess_years$name <- c(
  rep(c(rep('NJASK', 6), 'HSPA'), 7), 
  rep(c(rep('NJASK', 5),'GEPA', 'HSPA'), 2), 
  rep(c('NJASK', 'NJASK', 'GEPA', 'HSPA'), 2)
)

all_assess_raw <- list()

for (i in 1:nrow(assess_years)) {
  print(i)
  this_row <- assess_years[i, ]
  this_file <- readRDS(file = paste0('nj-raw/nj', this_row$year, 'gr', this_row$grade, '.Rds'))
  all_assess_raw[[i]] <- this_file
}

assess_clean <- list()
for (i in 1:length(all_assess_raw)) {
  print(i)
  assess_clean[[i]] <- tidy_nj_assess(assess_years[i, 'name'], all_assess_raw[[i]])
}
```

put the parsed into one data frame

```{r}

all_assess_tidy <- dplyr::rbind_all(assess_clean)

```
