---
title: "sysdata generation"
author: "Andrew Martin"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fetching all NJ data}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

just some documentation of what I've saved to ~~`sysdata.Rda`~~ various `.Rda` files

```{r silent1, echo=F, results='hide', message=F}
#libraries and functions etc
require(knitr)
#switch this to run the vignette
knitr::opts_knit$set(eval = FALSE)
```


#ASSESSMENT
(run everything in new_all_assess.Rmd)

#ENROLLMENT

```{r sys1}

enr_files <- list()

for (i in c(2015:1999)) {
  enr <- fetch_enr(i) 
  
  enr_files[[paste0('enr', i)]] <- enr
}

```

## rbind enr together

```{r enr2}

enr_all <- enr_files[["enr2015"]]

for (i in names(enr_files)[2:length(enr_files)]) {
  print(i)
  enr_all <- dplyr::rbind_all(list(enr_all, enr_files[[i]]))

  print(nrow(enr_all))
} 

```

# HS GRAD
```{r hs_grad}

hs_list <- list()
for (i in c(1998:2014)) {
  print(i)
  hs_list[[i]] <- fetch_grate(i)
}

hs_grad <- dplyr::rbind_all(hs_list)

```


```{r sys2}

save(enr_files, file = 'data\\enr_files.Rda')
save(enr_all, file = 'data\\enr_all.Rda')
save(hs_grad, file = 'data\\hs_grad.Rda')
save(all_assess_raw, file = 'data\\all_assess_raw.Rda')
save(all_assess_tidy, file = 'data\\all_assess_tidy.Rda')

```

#prog codes need padded zeros

```{r prog}

library(stringr)

prog_codes <- readr::read_csv(file.path('data-raw', 'program_codes_clean.csv'))

prog1 <- prog_codes[prog_codes$end_year >= 2010, ]
prog2 <- prog_codes[prog_codes$end_year < 2010, ]
prog2$program_code <- as.numeric(prog2$program_code) * 1

prog1$program_code <- stringr::str_pad(
  prog1$program_code, width = 2, side = 'left', pad = '0'
)

prog_codes <- rbind(prog1, prog2)

save(prog_codes, file = 'data\\program_codes.Rda')

```

### for debugging; step through fetch_enr steps

```{r debugging, eval = FALSE}

foo1 <-  get_raw_enr(2009) 
foo2 <- foo1 %>% clean_enr_names()
foo3 <- foo2 %>% split_enr_cols()
foo4 <- foo3 %>% clean_enr_data()
foo5 <- foo4 %>% process_enr_program()
foo6 <- foo5 %>% arrange_enr()
  
```  

