# Generated by scripts/source-validation/generate.py
"""Package-local source-validation release identity."""

SOURCE_VALIDATION_RELEASE = "source-validation-v1.0.0-rc.4"
CONTRACT_FINGERPRINT = "sha256:01384c3db08d508e202060996643cbf1f7c9c5b00c3d268f1fcb2ae97264b6f8"
ARTIFACT_MANIFEST_DIGEST = "sha256:a504663075c50fa7459965fc3a641935bac19e7fce0b67c6490dc915e46f5d8b"
EXPECTED_TEST_IDS = ["SV-001","SV-002","SV-003","SV-004","SV-005","SV-006","SV-007","SV-008","SV-009","SV-010","SV-011","SV-012","SV-013","SV-014","SV-015","SV-016","SV-017"]
