# Generated by scripts/source-validation/generate.py
test_that("source-validation new_jersey_shipped_sources identity matches the package", {
  expected_ids <- c("SV-001", "SV-002", "SV-003", "SV-004", "SV-005", "SV-006", "SV-007", "SV-008", "SV-009", "SV-010", "SV-011", "SV-012", "SV-013", "SV-014", "SV-015", "SV-016", "SV-017")
  expect_gt(length(expected_ids), 0L)
  expect_identical(length(unique(expected_ids)), length(expected_ids))

  # The generated module compiled into this package must carry the identity the
  # generator recorded here. Divergence means the two were written by different
  # generator runs.
  expect_identical(.source_validation_new_jersey_shipped_sources_release, "source-validation-v1.0.0-rc.4")
  expect_identical(.source_validation_new_jersey_shipped_sources_fingerprint, "sha256:56268bca5e5681a997d0dc3922c6414953a433020d8467e5f6f49c6be12cdd53")
  expect_identical(
    .source_validation_new_jersey_shipped_sources_manifest_digest, "sha256:a504663075c50fa7459965fc3a641935bac19e7fce0b67c6490dc915e46f5d8b"
  )
  expect_identical(
    .source_validation_new_jersey_shipped_sources_expected_test_ids, expected_ids
  )

  # The release lock is read from the INSTALLED package on disk, not from a
  # constant compiled into this file, so this block goes red on real drift.
  lock <- source_validation_new_jersey_shipped_sources_status()
  expect_identical(lock$contract_id, "new_jersey_shipped_sources")
  expect_identical(lock$source_validation_release, "source-validation-v1.0.0-rc.4")
  expect_identical(lock$contract_fingerprint, "sha256:56268bca5e5681a997d0dc3922c6414953a433020d8467e5f6f49c6be12cdd53")
  expect_identical(lock$artifact_manifest_digest, "sha256:a504663075c50fa7459965fc3a641935bac19e7fce0b67c6490dc915e46f5d8b")
  expect_identical(
    vapply(lock$expected_test_ids, as.character, character(1L), USE.NAMES = FALSE),
    expected_ids
  )
})
