# Generated by scripts/source-validation/generate.py
.source_validation_new_jersey_shipped_sources_release <- "source-validation-v1.0.0-rc.4"
.source_validation_new_jersey_shipped_sources_fingerprint <- "sha256:2f37d3ac1e6dbb64636590ec20934e8827fd13caa41852e2ca5e364054a5ce40"
.source_validation_new_jersey_shipped_sources_manifest_digest <- "sha256:a504663075c50fa7459965fc3a641935bac19e7fce0b67c6490dc915e46f5d8b"
.source_validation_new_jersey_shipped_sources_expected_test_ids <- c("SV-001", "SV-002", "SV-003", "SV-004", "SV-005", "SV-006", "SV-007", "SV-008", "SV-009", "SV-010", "SV-011", "SV-012", "SV-013", "SV-014", "SV-015", "SV-016", "SV-017")

source_validation_new_jersey_shipped_sources_status <- function() {
  lock <- system.file("extdata", "source-contract", "contracts", "new_jersey_shipped_sources", "release-lock.json", package = utils::packageName())
  if (!nzchar(lock)) stop("source-validation release lock is not installed", call. = FALSE)
  jsonlite::fromJSON(lock, simplifyVector = FALSE)
}
